---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

# **Growth as a data scientist:**

Prior to enrolling in this class, my experience with data analytics through R was limited to working with distributions and simulations. However, after completing this course, I am proud to say that I have acquired a new set of skills, knowledge and great connections. Not only did I learn a lot, but the expertise acquired in this class are also being applied to an extra-curricular project that I am currently working on. Beyond that, I believe that attention to detail with the conciseness of plot and axis labels, as well as cleanliness of the code are equally as important as the technical aspects of this course. Early on in the quarter, I struggled with paying attention to small details - axis labels, plot titles, new lines, quarto options. But as we progressed later on, I was able develop my skills in the said areas. I believe to have shown improvement in these aspects through the later labs and challenges (7, 8, 9), where I made sure to build graphs with no redundant plot labels and are clear and easy for the readers to take in. In challenge 7, there were abbreviations of some of the trout species which may possibly interfere with the reader's understanding. Because of that, I modified the display name for each species so that my readers are able to understand what they are looking at. I also use Quarto options with table of contents just to make it easier for my peers and instructor to navigate through the document. In these labs, I also believe to have demonstrated improvement on cleanliness and spacing. As a data scientist who will be sharing and working on the same code with peers, and reporting summaries in the future, being able to produce concise and neat results are important. In my extra-curricular research project, I am in charge of cleaning, transforming, and analyzing survey data collected from approximately 500 college students with over 100 columns to start with. Apart from doing the code alone, I also had to demonstrate my code to my research advisor, and build visualizations for my research leader and group. As an aspiring data scientist, I understand that apart from coding, a big part of my job will also be conveying, which is why it is important to make sure that the other side (audience, readers, & peers) will also be able to understand reports. Most of the methods being applied into my role for the project are concepts learned in this class.
